name: Sanity
 
on:
  push:
    branches:
      - '!main'
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches:
      - main
    paths:
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
